# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 861b13909495dbeb43b6352a2e34056224589e796f9164a668e8604a318f0a6c12e8a9b11c0ba900d0d88e8a72d683ecd4aaf34f00e9b6c311a003932a7040a2

test:
  secret_key_base: 8bc96c0a19a37bf7b0d500ca3b485bd317f065b4f90df6c50b06d41bb3a5fe248064bdb2f6811db88271dfd2cc430d2ddafd2d4d26468f9cb9125b6b51a91f22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
